//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMLSD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ticket()
        {
            this.TicketWIthMuseums = new HashSet<TicketWIthMuseum>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid OrderID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public System.Guid PassTypeiD { get; set; }
        public System.Guid PassAgeID { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual PassAge PassAge { get; set; }
        public virtual PassType PassType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketWIthMuseum> TicketWIthMuseums { get; set; }
    }
}
