//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMLSD
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketWIthMuseum
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> TicketID { get; set; }
        public Nullable<System.Guid> MuseumID { get; set; }
    
        public virtual Museum Museum { get; set; }
        public virtual Ticket Ticket { get; set; }
    }
}
